name: awesome-lint
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx awesome-lint
        name: "Run the awesome-lint linter"
